/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  tutorialSidebar: [
    'Om Enigma',
    'ITØK',
    {
      type: 'category',
      label: 'Styret',
      items: ['Styret/Styret H23', 'Styret/Styret H22', 'Styret/Styret H21'],
    },
    {
      type: 'category',
      label: 'Komitèer',
      items: ['Komiteer/Arrangement', 'Komiteer/Bedrift', 'Komiteer/SoMe']
    },
    {
      type: 'category',
      label: 'Interessegrupper',
      items: ['Interessegrupper/Fintech Enigma', 'Interessegrupper/Enigma Bryggelag', 'Interessegrupper/Enigma Turgruppe', 'Interessegrupper/Enigma Badeklubb']
    },
    {
      type: 'category',
      label: 'For Studenter',
      items: ['For Studenter/Ny Student']
    },
    {
      type: 'category',
      label: 'For Bedrifter',
      items: ['For Bedrifter/Bedriftspresentasjon med Enigma']
    },
    {
      type: 'category',
      label: 'Partnere',
      items: ['Partnere/Stacc']
    },
  ],
   
};

export default sidebars;
