/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  tutorialSidebar: [
    'Om Enigma',
    'ITØK',
    'Studiets oppbygging',
    {
      type: 'category',
      label: 'Styret',
      items: ['Styret/Styret H25', 'Styret/Styret H24','Styret/Styret H23',  'Styret/Styret H22', 'Styret/Styret H21']
    },
    {
      type: 'category',
      label: 'Komitéer',
      items: ['Komiteer/Arrangement', 'Komiteer/Bedrift', 'Komiteer/SoMe']
    },
    {
      type: 'category',
      label: 'Undergrupper',
      items: ['Undergrupper/Fintech Enigma', 'Undergrupper/Enigma Badeklubb', 'Undergrupper/Enigma Turgruppe', 'Undergrupper/Enigma Bryggelag', 'Undergrupper/Enigma Futsal', 'Undergrupper/Start en ny undergruppe']
    },
    {
      type: 'category',
      label: 'For studenter',
      items: ['For Studenter/Ny Student', 'For Studenter/Tilbakemeldinger', 'For Studenter/Tips og Triks', 'For Studenter/Ledige Stillinger', 'For Studenter/Vedtekter']
    },
    {
      type: 'category',
      label: 'For bedrifter',
      items: ['For Bedrifter/Kontakt oss', 'For Bedrifter/Hovedsamarbeidspartner', 'For Bedrifter/Bedriftspresentasjon med Enigma', 'For Bedrifter/Promotering',  'For Bedrifter/Logo']
    },
    {
      type: 'category',
      label: 'Partnere',
      items: ['Partnere/Stacc']
    }
  ]
   
};

export default sidebars;
